# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpc.facethink_pb2 as facethink__pb2


class grpcServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.process = channel.unary_unary(
        '/facethink.grpcServer/process',
        request_serializer=facethink__pb2.DataProto.SerializeToString,
        response_deserializer=facethink__pb2.ModelProto.FromString,
        )


class grpcServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def process(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_grpcServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'process': grpc.unary_unary_rpc_method_handler(
          servicer.process,
          request_deserializer=facethink__pb2.DataProto.FromString,
          response_serializer=facethink__pb2.ModelProto.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'facethink.grpcServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
